const getters = {
    userInfo: (state) => state.user.userInfo,
    token: (state) => state.user.userInfo.token,
    roles: state => state.user.userInfo.permissions,
    userNo: (state) => state.user.userInfo.userNo,
    clientid: (state) => state.user.userInfo.clientId,
    loginAccount: (state) => state.user.userInfo.loginAccount,
    userType: (state) => state.user.userInfo.userType,
    addRouters: state => state.permission.addRouters,
    sidebar: state => state.app.sidebar,
    sysTitle: (state) => state.app.sysTitle,
    language: state => state.app.language,
    device: state => state.app.device,
    visitedViews: state => state.tagsView.visitedViews,
    cachedViews: state => state.tagsView.cachedViews,
    // token: state => state.user.token,
    avatar: state => state.user.avatar,
    name: state => state.user.name,
    introduction: state => state.user.introduction,
    status: state => state.user.status,
    setting: state => state.user.setting,
    permission_routers: state => state.permission.routers,
    errorLogs: state => state.errorLog.logs
};
export default getters;
